In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [ ]:
train.head

In [5]:
#Checking 4 D features containing Nan
for i in train:
  if train[i].isnull().values.any() == True:
    print(i)

Age


# pre 1

In [6]:
# LabelEncoder
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(train['Sex'])
print(le.classes_)
print(le.transform(['male', 'female', 'female']))
print(le.inverse_transform([0, 0, 1, 1]))

['female' 'male']
[1 0 0]
['female' 'female' 'male' 'male']


In [7]:
for i in train:
  L = []
  for j in range(len(train[i])):
    L.append(train[i][j])
  for j in range(len(test[i])):
    L.append(test[i][j])
  le.fit(L)
  transformed_x = le.transform(train[i])
  train[i] = transformed_x
  transformed_y = le.transform(test[i])
  test[i] = transformed_y

# pre 2

In [8]:
#nan: 88
#Buildig an array to fit LR
#Pre 1
L = []
for i in range(len(train['Age'])):
  if train['Age'][i] == 88:
    L.append(i)
LL = []
for i in range(len(test['Age'])):
  if test['Age'][i] == 88:
    LL.append(i)

In [9]:
train_array = np.array(train)
test_array = np.array(test)

In [10]:
lr_X = train_array
lr_X = np.delete(lr_X, 2, axis=1)
lr_X = np.delete(lr_X, L, axis=0)

In [11]:
print(lr_X.shape)

(568, 8)


In [12]:
lr_Y = train_array.T[2]
lr_Y = np.delete(lr_Y, L)

In [13]:
reg = LinearRegression().fit(lr_X, lr_Y)

In [14]:
reg.score(lr_X, lr_Y)

0.2622532500967413

In [15]:
#Inject the predictions into train & test
to_pred_train = train_array[L]
to_pred_test = test_array[LL]

to_pred_train = np.delete(to_pred_train, 2 , axis=1)
to_pred_test = np.delete(to_pred_test, 2, axis=1)

pred_train = reg.predict(to_pred_train)
pred_train = pred_train.astype(int)
pred_test = reg.predict(to_pred_test)
pred_test = pred_test.astype(int)

print(pred_train)
print(pred_test)

[17 38 37 58 29 49 35 49 37 49 35 31 31 32 36 31 28 38 49 35 35 29 37 38
 37 32 32 44 19 38 59 44 38 49 38 29 58 36 36 29 46 36 38 38 36 45 34 37
 47 37 23 58 37 23 38 35 38 37 45 38 35 47 29 37 20 25 29 38 38 60 38 58
 37 26 58 57 37 31 38 35 37 23 24 58  6 49 29 31  5 23 29  5 57 39 29 39
 23 18 29 49 24 38 49 38 32 38 56 39 30 35 35 37 23 35 21 29 38 49 33 38
 40 42 57 38 37 39 49 37 38 27 37 57 49 35 37  6 38 60 25 29 38 32 37 40]
[38 38 23 39 28 49 39 47  6 35 38 36  5 38 38 35 35 28 37 27 38 55 19 38
  5 28 39 28 38 26 26 60 36]


In [16]:
U = []
for j in range(len(train['Age'])):
  U.append(train['Age'][j])
for j in range(len(test['Age'])):
  U.append(test['Age'][j])

In [17]:
le.fit(U)
pred_train = le.transform(pred_train)
pred_test = le.transform(pred_test)

In [18]:
#Pred 2
for i in range(len(L)):
  train_array[L[i]][2] = pred_train[i]

for i in range(len(LL)):
  test_array[LL[i]][2] = pred_test[i]

# Gausian Naive bayes to predict

In [19]:
from sklearn.naive_bayes import GaussianNB

In [20]:
X_train = train_array.T[:8].T
X_test = test_array.T[:8].T
y_train = train_array.T[8].T
y_test = test_array.T[8].T

In [21]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [22]:
print(y_pred[:20])
print(y_test[:20])

[1 0 1 1 1 0 0 1 1 1 0 0 1 0 1 1 0 0 0 1]
[1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 0 0 0 1]


# metrics

In [24]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print('accuracy: ', accuracy_score(y_test, y_pred))
print('precision: ', precision_score(y_test, y_pred))
print('recall: ', recall_score(y_test, y_pred))
print('f1_score: ', f1_score(y_test, y_pred))

accuracy:  0.7597765363128491
precision:  0.7027027027027027
recall:  0.7123287671232876
f1_score:  0.7074829931972789


In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
confusion_matrix(y_test, y_pred)

array([[84, 22],
       [21, 52]])